# Imports

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
import tabulate
import tensorflow as tf
from keras.models import Sequential
import pandas as pd
from keras.layers import Dense
from sklearn.model_selection import train_test_split


# from sklearn.metrics import accuracy_score , confusion_matrix , precision_score , recall_score , f1_score , classification_report , auc , roc_curve , ConfusionMatrixDisplay ,  roc_auc_score
# from sklearn.utils import resample
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.linear_model import LinearRegression , LogisticRegression
# from sklearn.preprocessing import LabelEncoder , RobustScaler , StandardScaler
# from sklearn.neural_network import MLPClassifier

from sklearn.preprocessing import RobustScaler,LabelEncoder

plt.style.use("fivethirtyeight")
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/financial-risk-for-loan-approval/Loan.csv
/kaggle/input/financial-risk-for-loan-approval/CSV Generation.py
/kaggle/input/regression-test-file/Regression_test_file.csv

In [2]:
loan = pd.read_csv("/kaggle/input/financial-risk-for-loan-approval/Loan.csv")
testFile = pd.read_csv("/kaggle/input/regression-test-file/Regression_test_file.csv")
copy = loan.copy()

In [3]:
copy.describe()

,Age,AnnualIncome,CreditScore,Experience,LoanAmount,LoanDuration,NumberOfDependents,MonthlyDebtPayments,CreditCardUtilizationRate,NumberOfOpenCreditLines,...,MonthlyIncome,UtilityBillsPaymentHistory,JobTenure,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,LoanApproved,RiskScore
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,...,20000.000000,20000.000000,20000.000000,2.000000e+04,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,39.752600,59161.473550,571.612400,17.522750,24882.867800,54.057000,1.517300,454.292700,0.286381,3.023350,...,4891.715521,0.799918,5.002650,7.229432e+04,0.239124,0.239110,911.607052,0.402182,0.239000,50.766780
std,11.622713,40350.845168,50.997358,11.316836,13427.421217,24.664857,1.386325,240.507609,0.159793,1.736161,...,3296.771598,0.120665,2.236804,1.179200e+05,0.035509,0.042205,674.583473,0.338924,0.426483,7.778262
min,18.000000,15000.000000,343.000000,0.000000,3674.000000,12.000000,0.000000,50.000000,0.000974,0.000000,...,1250.000000,0.259203,0.000000,1.000000e+03,0.130101,0.113310,97.030193,0.016043,0.000000,28.800000
25%,32.000000,31679.000000,540.000000,9.000000,15575.000000,36.000000,0.000000,286.000000,0.160794,2.000000,...,2629.583333,0.727379,3.000000,8.734750e+03,0.213889,0.209142,493.763700,0.179693,0.000000,46.000000
50%,40.000000,48566.000000,578.000000,17.000000,21914.500000,48.000000,1.000000,402.000000,0.266673,3.000000,...,4034.750000,0.820962,5.000000,3.285550e+04,0.236157,0.235390,728.511452,0.302711,0.000000,52.000000
75%,48.000000,74391.000000,609.000000,25.000000,30835.000000,72.000000,2.000000,564.000000,0.390634,4.000000,...,6163.000000,0.892333,6.000000,8.882550e+04,0.261533,0.265532,1112.770759,0.509214,0.000000,56.000000
max,80.000000,485341.000000,712.000000,61.000000,184732.000000,120.000000,5.000000,2919.000000,0.917380,13.000000,...,25000.000000,0.999433,16.000000,2.603208e+06,0.405029,0.446787,10892.629520,4.647657,1.000000,84.000000

In [4]:
copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ApplicationDate             20000 non-null  object
 1   Age                         20000 non-null  int64
 2   AnnualIncome                20000 non-null  int64
 3   CreditScore                 20000 non-null  int64
 4   EmploymentStatus            20000 non-null  object
 5   EducationLevel              20000 non-null  object
 6   Experience                  20000 non-null  int64
 7   LoanAmount                  20000 non-null  int64
 8   LoanDuration                20000 non-null  int64
 9   MaritalStatus               20000 non-null  object
 10  NumberOfDependents          20000 non-null  int64
 11  HomeOwnershipStatus         20000 non-null  object
 12  MonthlyDebtPayments         20000 non-null  int64
 13  CreditCardUtilizationRate   20000 non-null  float64
 14  NumberOfOpenCreditLines     20000 non-null  int64
 15  NumberOfCreditInquiries     20000 non-null  int64
 16  DebtToIncomeRatio           20000 non-null  float64
 17  BankruptcyHistory           20000 non-null  int64
 18  LoanPurpose                 20000 non-null  object
 19  PreviousLoanDefaults        20000 non-null  int64
 20  PaymentHistory              20000 non-null  int64
 21  LengthOfCreditHistory       20000 non-null  int64
 22  SavingsAccountBalance       20000 non-null  int64
 23  CheckingAccountBalance      20000 non-null  int64
 24  TotalAssets                 20000 non-null  int64
 25  TotalLiabilities            20000 non-null  int64
 26  MonthlyIncome               20000 non-null  float64
 27  UtilityBillsPaymentHistory  20000 non-null  float64
 28  JobTenure                   20000 non-null  int64
 29  NetWorth                    20000 non-null  int64
 30  BaseInterestRate            20000 non-null  float64
 31  InterestRate                20000 non-null  float64
 32  MonthlyLoanPayment          20000 non-null  float64
 33  TotalDebtToIncomeRatio      20000 non-null  float64
 34  LoanApproved                20000 non-null  int64
 35  RiskScore                   20000 non-null  float64
dtypes: float64(9), int64(21), object(6)
memory usage: 5.5+ MB

In [5]:
copy.isna().sum()

ApplicationDate               0
Age                           0
AnnualIncome                  0
CreditScore                   0
EmploymentStatus              0
EducationLevel                0
Experience                    0
LoanAmount                    0
LoanDuration                  0
MaritalStatus                 0
NumberOfDependents            0
HomeOwnershipStatus           0
MonthlyDebtPayments           0
CreditCardUtilizationRate     0
NumberOfOpenCreditLines       0
NumberOfCreditInquiries       0
DebtToIncomeRatio             0
BankruptcyHistory             0
LoanPurpose                   0
PreviousLoanDefaults          0
PaymentHistory                0
LengthOfCreditHistory         0
SavingsAccountBalance         0
CheckingAccountBalance        0
TotalAssets                   0
TotalLiabilities              0
MonthlyIncome                 0
UtilityBillsPaymentHistory    0
JobTenure                     0
NetWorth                      0
BaseInterestRate              0
InterestRate                  0
MonthlyLoanPayment            0
TotalDebtToIncomeRatio        0
LoanApproved                  0
RiskScore                     0
dtype: int64

In [6]:
copy.duplicated().sum()

0

In [7]:
copy = copy.drop(columns = "ApplicationDate")
copy.drop_duplicates()
copy.dropna()

,Age,AnnualIncome,CreditScore,EmploymentStatus,EducationLevel,Experience,LoanAmount,LoanDuration,MaritalStatus,NumberOfDependents,...,MonthlyIncome,UtilityBillsPaymentHistory,JobTenure,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,LoanApproved,RiskScore
0,45,39948,617,Employed,Master,22,13152,48,Married,2,...,3329.000000,0.724972,11,126928,0.199652,0.227590,419.805992,0.181077,0,49.0
1,38,39709,628,Employed,Associate,15,26045,48,Single,1,...,3309.083333,0.935132,3,43609,0.207045,0.201077,794.054238,0.389852,0,52.0
2,47,40724,570,Employed,Bachelor,26,17627,36,Married,2,...,3393.666667,0.872241,6,5205,0.217627,0.212548,666.406688,0.462157,0,52.0
3,58,69084,545,Employed,High School,34,37898,96,Single,1,...,5757.000000,0.896155,5,99452,0.300398,0.300911,1047.506980,0.313098,0,54.0
4,37,103264,594,Employed,Associate,17,9184,36,Married,1,...,8605.333333,0.941369,5,227019,0.197184,0.175990,330.179140,0.070210,1,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,44,30180,587,Employed,High School,19,24521,36,Married,3,...,2515.000000,0.826217,1,55327,0.216021,0.195574,905.767712,0.627741,0,55.0
19996,56,49246,567,Employed,Associate,33,25818,36,Married,5,...,4103.833333,0.816618,3,64002,0.227318,0.199168,958.395633,0.334418,0,54.0
19997,44,48958,645,Employed,Bachelor,20,37033,72,Married,3,...,4079.833333,0.887216,3,103663,0.229533,0.226766,945.427454,0.357227,0,45.0
19998,60,41025,560,Employed,High School,36,14760,72,Married,3,...,3418.750000,0.843787,5,10600,0.249760,0.264873,411.168284,0.408678,0,59.0
19999,20,53227,574,Employed,Associate,0,32055,48,Married,0,...,4435.583333,0.853801,5,41372,0.240055,0.242693,1049.830407,0.298006,0,59.0

In [8]:
listOfColumns = []

listOfCategoricalColumns = []
for i in copy.select_dtypes(include = 'number'):
    listOfColumns.append(i)


for j in copy.columns:

    if j not in listOfColumns:
        listOfCategoricalColumns.append(j)
le = LabelEncoder()
for i in listOfCategoricalColumns:
    copy[i] = le.fit_transform(copy[i])

X_Loan = copy.drop(columns = ['RiskScore'])
Y_Loan = copy["RiskScore"]
copy
robust = RobustScaler()
scaledX = robust.fit_transform(X_Loan)
scaledY = robust.fit_transform(Y_Loan.values.reshape(-1,1))
robust = RobustScaler()
scaledXLoan = robust.fit_transform(X_Loan)
scaledYLoan = robust.fit_transform(Y_Loan.values.reshape(-1,1))

In [9]:
testFile = testFile.drop(columns = "ApplicationDate")
testFile.drop_duplicates()
testFile.dropna()
listOfColumns = []

listOfCategoricalColumns = []
for i in testFile.select_dtypes(include = 'number'):
    listOfColumns.append(i)


for j in testFile.columns:

    if j not in listOfColumns:
        listOfCategoricalColumns.append(j)
le = LabelEncoder()
for i in listOfCategoricalColumns:
    testFile[i] = le.fit_transform(testFile[i])





robust_TestFile = RobustScaler()
scaledXTestFile = robust_TestFile.fit_transform(testFile)

In [10]:
X_train, X_val, y_train, y_val = train_test_split( scaledXLoan, scaledYLoan, test_size=0.2, random_state=42)

In [11]:
import tensorflow as tf
from keras.models import Sequential
import pandas as pd
from keras.layers import Dense
from tensorflow.keras.optimizers import Adam
model = Sequential()
model.add(Dense(100, activation='relu', input_dim = X_train.shape[1]))

model.add(Dense(1))
model.compile(optimizer=Adam(learning_rate=0.001), loss='mean_squared_error')
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_val, y_val))
print(model.evaluate(X_val, y_val))

Epoch 1/10

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2338 - val_loss: 0.0353
Epoch 2/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0312 - val_loss: 0.0284
Epoch 3/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0244 - val_loss: 0.0245
Epoch 4/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0206 - val_loss: 0.0220
Epoch 5/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0194 - val_loss: 0.0213
Epoch 6/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0185 - val_loss: 0.0198
Epoch 7/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0171 - val_loss: 0.0199
Epoch 8/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.0171 - val_loss: 0.0189
Epoch 9/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0157 - val_loss: 0.0188
Epoch 10/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.0152 - val_loss: 0.0187
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0186
0.01869373954832554

In [12]:
predections_Adam = np.argmax(model.predict(scaledXTestFile), axis=1)
print(predections_Adam)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]

In [13]:
# with open("Trial 1.txt", "w") as fp:
#     fp.writelines('%s\n' % value for value in plotly_callback.val_loss)
#     fp.write("\nValidation Accuracy:\n")
#     fp.writelines('%s\n' % value for value in plotly_callback.val_accuracy)

In [14]:
# existing_files = [f for f in os.listdir("/Phase_2/Predictions") if f.endswith('.csv')]
# testFile = pd.read_csv("/kaggle/input/classification-test-file/Regression_test_file.csv")
# testFile_scaled = scaler.transform(testFile)
# y_pred_multiclassAdam = np.argmax(modelAdam.predict(testFile_scaled), axis=1)
# dictt = {
#     "ID": [i for i in range(len(testFile))],
#     "Class": y_pred_multiclassAdam
# }
# df = pd.DataFrame(dictt)
# output_file_path = os.path.join(predictions_dir, f"Task-2 Trial ({len(existing_files) + 1 }).csv")
# df.to_csv(output_file_path, index=False)